### ISSUE TITLE
Actualización automática de la documentación

### ISSUE THREAD

**Issue by elecyb** [enzonotario/criptoya-api-docs#2]
Sería ideal que la documentación se actualice automáticamente cuando se agregan/quitan exchanges.
Endpoint para obtener los exchange de cada país: https://criptoya.com/api/exchanges

Faltan **cryptomktpro** (ar, br, cl, co, pe) y **coinexp2p** (ar, br, cl, co, mx, pe, uy, bo, do, py, ve)

**Comment by enzonotario** [comment]
Hola @elecyb , ya actualice el Script para que tome los Exchanges desde este Endpoint.

Por lo pronto, la "actualizacion automatica" se puede ejecutar desde GitHub Actions (ahi te agregué como Colaborador). Esta Action se puede ejecutar de manera manual en cualquier momento desde: https://github.com/enzonotario/criptoya-api-docs/actions/workflows/generate-docs.yaml

También es posible [disparar esta Action por medio de la API](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event), que podrias agregarlo para que se ejecute en el momento que se actualiza la API.

Saludos!
