### ISSUE TITLE
Redondeo de precios

### ISSUE THREAD

**Issue by diegoviscovig** [enzonotario/criptoya-api-docs#6]
Hola, primero felicitacion por la api, pero tenes un tema con los redondeos, sobre todo en monedas donde los numeros son pequelños como SHIB
El conversor de SHIB real es 0.01754 y la api devuelve 0.02, para todos los exchanges. El tema que en SHIB ese redondeo es muy grande, ya que shiba son miles por dolar
Saludos y felicitaciones nuevamente por la api.

**Comment by enzonotario** [comment]
Hola @diegoviscovig , genial muchas gracias por reportarlo!

Aunque este repositorio sólo es referido a la Documentación de la API (https://docs.criptoya.com/), y no a la API propiamente dicha y su contenido (https://criptoya.com/api).

Voy a intentar llevárselo a la gente que gestiona la API, o veremos si @elecyb puede gestionar este Issue, sino procederé a cerrarlo. 

También voy a aclarar esto en el Template de los Issues, ya que el contacto oficial de la API sería contacto@criptoya.com

Saludos!

**Comment by elecyb** [comment]
Hola @diegoviscovig , ya está arreglado!

Muchas gracias por el reporte.
Saludos
